baseurl: '/'
permalink: pretty
title: 'Synergy HR Consulting Group'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'Based on a Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Synergy HR Consulting Group"
  meta_og_type: "website"
  meta_og_url: "https://www.synergyhrgroup.in/"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Synergy HR Consulting Group is a team of management professionals dedicated to the vision of evolving a Total Problem Solution in the field of STRATEGY, HRD, OD, TQM & executive coaching in the process multiplying an organization’s talent nucleus and human capital, two vital pillars in creating a globally competitive benchmark organization."

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

kramdown:
  parse_html_block: true
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md